//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backlang.Codeanalysis.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backlang.Codeanalysis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected Identifier, TupleType or Function-Signature as TypeLiteral, but got {0} ähnelt.
        /// </summary>
        internal static string BL1 {
            get {
                return ResourceManager.GetString("BL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected Type but got {0} ähnelt.
        /// </summary>
        internal static string BL10 {
            get {
                return ResourceManager.GetString("BL10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected Switch Option ähnelt.
        /// </summary>
        internal static string BL11 {
            get {
                return ResourceManager.GetString("BL11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected at least one catch block ähnelt.
        /// </summary>
        internal static string BL12 {
            get {
                return ResourceManager.GetString("BL12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SourceFile is empty ähnelt.
        /// </summary>
        internal static string BL13 {
            get {
                return ResourceManager.GetString("BL13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected Identifier but got {0} ähnelt.
        /// </summary>
        internal static string BL14 {
            get {
                return ResourceManager.GetString("BL14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterminated String-Literal ähnelt.
        /// </summary>
        internal static string BL15 {
            get {
                return ResourceManager.GetString("BL15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiline comment is not closed ähnelt.
        /// </summary>
        internal static string BL16 {
            get {
                return ResourceManager.GetString("BL16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected &apos;{0}&apos; but got &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string BL17 {
            get {
                return ResourceManager.GetString("BL17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicate Modifier &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string BL18 {
            get {
                return ResourceManager.GetString("BL18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Modifier Combination ähnelt.
        /// </summary>
        internal static string BL2 {
            get {
                return ResourceManager.GetString("BL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Character &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string BL3 {
            get {
                return ResourceManager.GetString("BL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterminated Char-Literal ähnelt.
        /// </summary>
        internal static string BL4 {
            get {
                return ResourceManager.GetString("BL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected Expression {0} ähnelt.
        /// </summary>
        internal static string BL5 {
            get {
                return ResourceManager.GetString("BL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Literal {0} ähnelt.
        /// </summary>
        internal static string BL6 {
            get {
                return ResourceManager.GetString("BL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trailing comma is forbidden ähnelt.
        /// </summary>
        internal static string BL7 {
            get {
                return ResourceManager.GetString("BL7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitfield member declaration only allows literals ähnelt.
        /// </summary>
        internal static string BL8 {
            get {
                return ResourceManager.GetString("BL8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected Function, Property or Field-declaration for Type, but got {0} ähnelt.
        /// </summary>
        internal static string BL9 {
            get {
                return ResourceManager.GetString("BL9", resourceCulture);
            }
        }
    }
}
