//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backlang.Codeanalysis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backlang.Codeanalysis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Identifier, TupleType or Function-Signature as TypeLiteral, but got {0}.
        /// </summary>
        internal static string BL_0001_ {
            get {
                return ResourceManager.GetString("BL(0001)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Modifier Combination.
        /// </summary>
        internal static string BL_0002_ {
            get {
                return ResourceManager.GetString("BL(0002)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Character &apos;{0}&apos;.
        /// </summary>
        internal static string BL_0003_ {
            get {
                return ResourceManager.GetString("BL(0003)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated Char-Literal.
        /// </summary>
        internal static string BL_0004_ {
            get {
                return ResourceManager.GetString("BL(0004)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Expression {0}.
        /// </summary>
        internal static string BL_0005_ {
            get {
                return ResourceManager.GetString("BL(0005)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Literal {0}.
        /// </summary>
        internal static string BL_0006_ {
            get {
                return ResourceManager.GetString("BL(0006)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing comma is forbidden.
        /// </summary>
        internal static string BL_0007_ {
            get {
                return ResourceManager.GetString("BL(0007)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitfield member declaration only allows literals.
        /// </summary>
        internal static string BL_0008_ {
            get {
                return ResourceManager.GetString("BL(0008)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Function, Property or Field-declaration for Type, but got {0}.
        /// </summary>
        internal static string BL_0009_ {
            get {
                return ResourceManager.GetString("BL(0009)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Type but got {0}.
        /// </summary>
        internal static string BL_0010_ {
            get {
                return ResourceManager.GetString("BL(0010)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Switch Option.
        /// </summary>
        internal static string BL_0011_ {
            get {
                return ResourceManager.GetString("BL(0011)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected at least one catch block.
        /// </summary>
        internal static string BL_0012_ {
            get {
                return ResourceManager.GetString("BL(0012)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceFile is empty.
        /// </summary>
        internal static string BL_0013_ {
            get {
                return ResourceManager.GetString("BL(0013)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Identifier but got {0}.
        /// </summary>
        internal static string BL_0014_ {
            get {
                return ResourceManager.GetString("BL(0014)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated String-Literal.
        /// </summary>
        internal static string BL_0015_ {
            get {
                return ResourceManager.GetString("BL(0015)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiline comment is not closed.
        /// </summary>
        internal static string BL_0016_ {
            get {
                return ResourceManager.GetString("BL(0016)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;{0}&apos; but got &apos;{1}&apos;.
        /// </summary>
        internal static string BL_0017_ {
            get {
                return ResourceManager.GetString("BL(0017)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Modifier &apos;{0}&apos;.
        /// </summary>
        internal static string BL_0018_ {
            get {
                return ResourceManager.GetString("BL(0018)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace &apos;{0}&apos; already imported.
        /// </summary>
        internal static string BL_0019_ {
            get {
                return ResourceManager.GetString("BL(0019)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got OutputType &apos;Exe&apos; but couldn&apos;t find entry point..
        /// </summary>
        internal static string BL_0020_ {
            get {
                return ResourceManager.GetString("BL(0020)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be found. Did you mean &apos;{1}&apos;?.
        /// </summary>
        internal static string BL_0021_ {
            get {
                return ResourceManager.GetString("BL(0021)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot implement &apos;{0}&apos;, type not found.
        /// </summary>
        internal static string BL_0022_ {
            get {
                return ResourceManager.GetString("BL(0022)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot implement unit type &apos;{0}&apos;.
        /// </summary>
        internal static string BL_0023_ {
            get {
                return ResourceManager.GetString("BL(0023)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; already declared.
        /// </summary>
        internal static string BL_0024_ {
            get {
                return ResourceManager.GetString("BL(0024)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch {0} {1}.
        /// </summary>
        internal static string BL_0025_ {
            get {
                return ResourceManager.GetString("BL(0025)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type mismatch {0} {1}.
        /// </summary>
        internal static string BL_0026_ {
            get {
                return ResourceManager.GetString("BL(0026)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be resolved.
        /// </summary>
        internal static string BL_0027_ {
            get {
                return ResourceManager.GetString("BL(0027)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find function &apos;{0}&apos;.
        /// </summary>
        internal static string BL_0028_ {
            get {
                return ResourceManager.GetString("BL(0028)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target &apos;{0}&apos; cannot be found.
        /// </summary>
        internal static string BL_0029_ {
            get {
                return ResourceManager.GetString("BL(0029)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; is not defined.
        /// </summary>
        internal static string BL_0030_ {
            get {
                return ResourceManager.GetString("BL(0030)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set type.
        /// </summary>
        internal static string BL_0031_ {
            get {
                return ResourceManager.GetString("BL(0031)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deduce Type. Declare it manually!.
        /// </summary>
        internal static string BL_0032_ {
            get {
                return ResourceManager.GetString("BL(0032)", resourceCulture);
            }
        }
    }
}
