//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backlang.Codeanalysis.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backlang.Codeanalysis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected Identifier, TupleType or Function-Signature as TypeLiteral, but got {0} ähnelt.
        /// </summary>
        internal static string BL_0001_ {
            get {
                return ResourceManager.GetString("BL(0001)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Modifier Combination ähnelt.
        /// </summary>
        internal static string BL_0002_ {
            get {
                return ResourceManager.GetString("BL(0002)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Character &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string BL_0003_ {
            get {
                return ResourceManager.GetString("BL(0003)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterminated Char-Literal ähnelt.
        /// </summary>
        internal static string BL_0004_ {
            get {
                return ResourceManager.GetString("BL(0004)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected Expression {0} ähnelt.
        /// </summary>
        internal static string BL_0005_ {
            get {
                return ResourceManager.GetString("BL(0005)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Literal {0} ähnelt.
        /// </summary>
        internal static string BL_0006_ {
            get {
                return ResourceManager.GetString("BL(0006)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trailing comma is forbidden ähnelt.
        /// </summary>
        internal static string BL_0007_ {
            get {
                return ResourceManager.GetString("BL(0007)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitfield member declaration only allows literals ähnelt.
        /// </summary>
        internal static string BL_0008_ {
            get {
                return ResourceManager.GetString("BL(0008)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected Function, Property or Field-declaration for Type, but got {0} ähnelt.
        /// </summary>
        internal static string BL_0009_ {
            get {
                return ResourceManager.GetString("BL(0009)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected Type but got {0} ähnelt.
        /// </summary>
        internal static string BL_0010_ {
            get {
                return ResourceManager.GetString("BL(0010)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected Switch Option ähnelt.
        /// </summary>
        internal static string BL_0011_ {
            get {
                return ResourceManager.GetString("BL(0011)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected at least one catch block ähnelt.
        /// </summary>
        internal static string BL_0012_ {
            get {
                return ResourceManager.GetString("BL(0012)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SourceFile is empty ähnelt.
        /// </summary>
        internal static string BL_0013_ {
            get {
                return ResourceManager.GetString("BL(0013)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected Identifier but got {0} ähnelt.
        /// </summary>
        internal static string BL_0014_ {
            get {
                return ResourceManager.GetString("BL(0014)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterminated String-Literal ähnelt.
        /// </summary>
        internal static string BL_0015_ {
            get {
                return ResourceManager.GetString("BL(0015)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiline comment is not closed ähnelt.
        /// </summary>
        internal static string BL_0016_ {
            get {
                return ResourceManager.GetString("BL(0016)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected &apos;{0}&apos; but got &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string BL_0017_ {
            get {
                return ResourceManager.GetString("BL(0017)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicate Modifier &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string BL_0018_ {
            get {
                return ResourceManager.GetString("BL(0018)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Namespace &apos;{0}&apos; already imported ähnelt.
        /// </summary>
        internal static string BL_0019_ {
            get {
                return ResourceManager.GetString("BL(0019)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Got OutputType &apos;Exe&apos; but couldn&apos;t find entry point. ähnelt.
        /// </summary>
        internal static string BL_0020_ {
            get {
                return ResourceManager.GetString("BL(0020)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} cannot be found. Did you mean &apos;{1}&apos;? ähnelt.
        /// </summary>
        internal static string BL_0021_ {
            get {
                return ResourceManager.GetString("BL(0021)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot implement &apos;{0}&apos;, type not found ähnelt.
        /// </summary>
        internal static string BL_0022_ {
            get {
                return ResourceManager.GetString("BL(0022)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot implement unit type &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string BL_0023_ {
            get {
                return ResourceManager.GetString("BL(0023)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; already declared ähnelt.
        /// </summary>
        internal static string BL_0024_ {
            get {
                return ResourceManager.GetString("BL(0024)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type mismatch {0} {1} ähnelt.
        /// </summary>
        internal static string BL_0025_ {
            get {
                return ResourceManager.GetString("BL(0025)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unit Type mismatch {0} {1} ähnelt.
        /// </summary>
        internal static string BL_0026_ {
            get {
                return ResourceManager.GetString("BL(0026)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} cannot be resolved ähnelt.
        /// </summary>
        internal static string BL_0027_ {
            get {
                return ResourceManager.GetString("BL(0027)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot find function &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string BL_0028_ {
            get {
                return ResourceManager.GetString("BL(0028)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target &apos;{0}&apos; cannot be found ähnelt.
        /// </summary>
        internal static string BL_0029_ {
            get {
                return ResourceManager.GetString("BL(0029)", resourceCulture);
            }
        }
    }
}
